[package]
name = "weakauras_parser_base64"
version = "0.1.5"
authors = ["Velithris <13710677+Zireael-N@users.noreply.github.com>", "Wojciech Muła", "Alfred Klomp", "Daniel Lemire"]
edition = "2024"
license = "BSD-2-Clause"
