name: ci
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  code-check:
    name: code-check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, win-msvc, win-gnu]
        include:
        - build: linux
          os: ubuntu-20.04
          target: x86_64-unknown-linux-gnu
        - build: macos
          os: macos-latest
          target: x86_64-apple-darwin
        - build: win-msvc
          os: windows-2019
          target: x86_64-pc-windows-msvc
        - build: win-gnu
          os: windows-2019
          target: x86_64-pc-windows-gnu

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        target: ${{ matrix.target }}

    - name: Run cargo check
      run: cargo check

  code-style:
    name: code-style
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        target: x86_64-unknown-linux-musl

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Check clippy lints
      run: cargo clippy -- -D warnings
